### ISSUE TITLE
2022-04-06 "The 'Eccentric Kung Fu Master' School of Education" Comments

### ISSUE THREAD

**Issue by BennyQBD** [BennyQBD/thebennyblog#2]
Here's a place where you can leave comments and discussion for the post https://bennyqbd.github.io/thebennyblog/jekyll/update/2022/04/06/the-eccentric-kung-fu-master.html

**Comment by wcardozo** [comment]
Hi Benny,

Good to hear from you again.
Count on me to be your student.

Best Regards

**Comment by agausmann** [comment]
I can definitely relate to having a backlog of stuff to talk about. For me, it is all because I had left a series hanging after hitting a wall and losing interest, and I didn't really know how to handle it. I left my blog idle for 8 months just after (re)starting it, because I couldn't bring myself to write about anything else first. It took me that long to figure out that I should just talk about the problems I had faced, provide some closure, and move on.

**Comment by GeneRickUsername** [comment]
Hooh

**Comment by taurreco** [comment]
All of these projects sound very exciting!  Even if I have to wait 10 or 20 years before I get to read it all in, I'm happy knowing you are working as hard as you can to bring them to your standards.  Good luck!  You are an inspiration!
